### ISSUE TITLE
error[E0599]: no method named `getunmint_amount` found for struct `mercurial_vault::state::Vault` in the current scope

### ISSUE THREAD

**Issue by gitmalong** [mercurial-finance/mercurial-dynamic-amm-sdk#83]
--> /Users/user/.cargo/git/checkouts/mercurial-dynamic-amm-sdk-cff91a6a504f4f2c/beea115/programs/amm/src/utils.rs:160:10
    |
160 |         .getunmint_amount(
    |          ^^^^^^^^^^^^^^^^ help: there is a method with a similar name: `get_unmint_amount`

**Comment by gitmalong** [comment]
https://github.com/mercurial-finance/mercurial-dynamic-amm-sdk/blob/beea115ad35b7cc6c3c9fde441c02c4f0da87a0c/programs/amm/src/utils.rs#L160

**Comment by andrewsource147** [comment]
Thanks for report, fixed in PR https://github.com/mercurial-finance/mercurial-dynamic-amm-sdk/pull/85#pullrequestreview-1526096515
